# Generated by Django 2.0.7 on 2019-06-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('program_type', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
