# Generated by Django 2.2.2 on 2019-06-13 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20190613_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='end_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='period',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
