# Generated by Django 2.2.2 on 2019-06-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20190613_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='end_datetime',
            new_name='datetime_end',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='start_datetime',
            new_name='datetime_start',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='end_time',
            new_name='time_of_day_end',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='start_time',
            new_name='time_of_day_start',
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
