# Generated by Django 2.2.2 on 2019-06-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20190613_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('run-once', 'Run Once'), ('periodic', 'Periodic'), ('weekly', 'Weekly')], default='run-once', max_length=16),
        ),
    ]
