# Generated by Django 2.2.2 on 2019-06-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20190614_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='datetime_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='period',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='time_of_day_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='time_of_day_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
