# Generated by Django 2.2.2 on 2019-06-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_auto_20190614_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='priority',
            field=models.IntegerField(default=10),
        ),
    ]
