# Generated by Django 2.2.2 on 2019-06-17 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_auto_20190615_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='time_of_day_end',
            new_name='time_end',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='time_of_day_start',
            new_name='time_start',
        ),
        migrations.RemoveField(
            model_name='program',
            name='datetime_end',
        ),
        migrations.RemoveField(
            model_name='program',
            name='datetime_start',
        ),
        migrations.AddField(
            model_name='program',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
