# Generated by Django 2.2.2 on 2019-06-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_program_days_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='days_of_week',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Firday'), ('6', 'Saturday'), ('7', 'Sunday')], default='', max_length=16),
        ),
    ]
