# Generated by Django 2.2.2 on 2019-06-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_auto_20190617_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='days_of_week',
            field=models.CharField(default='', max_length=16),
        ),
    ]
