# Generated by Django 2.2.2 on 2019-06-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0012_auto_20190617_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('run-once', 'Run Once'), ('periodic', 'Periodic'), ('weekly', 'Weekly')], default='run-once', max_length=50),
        ),
    ]
