# Generated by Django 2.2.2 on 2019-06-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_auto_20190617_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='days_of_week',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('run-once', 'Run Once'), ('periodic', 'Periodic'), ('weekly', 'Weekly')], default='run-once', max_length=16),
        ),
    ]
