# Generated by Django 2.2.2 on 2019-07-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0003_controller_location'),
        ('programs', '0015_auto_20190618_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='channels',
            field=models.ManyToManyField(blank=True, null=True, to='controllers.Channel'),
        ),
    ]
