# Generated by Django 2.2.2 on 2019-07-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0016_program_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='channels',
            field=models.ManyToManyField(blank=True, to='controllers.Channel'),
        ),
    ]
