# Generated by Django 2.2.2 on 2019-07-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0017_auto_20190711_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='period',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
