# Generated by Django 2.2.2 on 2019-07-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0018_auto_20190716_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='days_of_week',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
