# Generated by Django 2.2.5 on 2019-10-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0020_remove_program_time_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='can_be_skipped',
            field=models.BooleanField(default=True),
        ),
    ]
