# Generated by Django 2.2.5 on 2019-10-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
        ('programs', '0022_remove_program_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='zones',
            field=models.ManyToManyField(blank=True, to='zones.Zone'),
        ),
    ]
