# Generated by Django 2.2.2 on 2019-07-16 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0004_auto_20190711_0542'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedrun',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='controllers.Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledrun',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='controllers.Channel'),
            preserve_default=False,
        ),
    ]
