# Generated by Django 2.2.2 on 2019-07-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20190716_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledrun',
            old_name='channel',
            new_name='zone',
        ),
    ]
